
all: p1 p2 p3 p4
ex: ex1 ex2 ex3 ex4

clean:
	rm -f p1 p2 p3 p4 ex1 ex2 ex3 ex4

ex1: ex1.c
	gcc -o ex1 ex1.c -Wall

ex2: ex2.c
	gcc -o ex2 ex2.c -Wall

ex3: ex3.c
	gcc -o ex3 ex3.c -Wall

ex4: ex4.c
	gcc -o ex4 ex4.c -Wall

p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

